apiVersion: v1
kind: ConfigMap
metadata:
  name: my-web-content
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Naganuma Home Lab</title>
        <style>
            body { font-family: sans-serif; text-align: center; padding: 50px; background: #f4f4f4; }
            h1 { color: #326ce5; }
            .node-info { background: white; padding: 20px; border-radius: 10px; display: inline-block; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        </style>
    </head>
    <body>
        <h1>Welcome to K8s Home Lab</h1>
        <div class="node-info">
            <p>このページは <strong>k3sクラスタ</strong> 上で動いています。</p>
            <p>Node: Proxmox Cluster (Ryzen/OptiPlex)</p>
        </div>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-website
  template:
    metadata:
      labels:
        app: my-website
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: my-web-content
